---
kind: secret
name: rocket_url
data: 94NqJOFYW/aTpiMBqTYtneg+gndYV7lzlln1gddzNCNRj1lUCBekLd9uu1VQ40PnIg1jIQ==

---
kind: secret
name: rocket_user
data: Jr0kh5fcITYxUhBTcl8IyMKRgFyLLW7ETZXTYDz7GMOFTq51W+w+dLgjjALW

---
kind: secret
name: rocket_token
data: pLYmJU/8SzADQ6kEuvOe2k+Jb0z+CZButPa/wsulcwJrBHcGc9Zq+HagMiHzRh5oQ4/zRchlHDZcVV++pJroHvqECHrnaD4=

---
kind: pipeline
name: default

steps:
  - name: install-backend
    image: composer:2.8.2
    depends_on: [ clone ]
    commands:
      - composer install --optimize-autoloader

  - name: backend-tests
    image: php:8.3.22-cli
    depends_on: [ install-backend ]
    commands:
      - ./vendor/bin/phpunit ./tests

  - name: notify
    image: mike1pol/drone-rocket
    depends_on: [ backend-tests ]
    settings:
      url: { from_secret: rocket_url }
      user_id: { from_secret: rocket_user }
      token: { from_secret: rocket_token }
      channel: github
    when:
      status: [ success, failure ]
    trigger:
      status: [ success, failure ]
      event:
        exclude: [ pull_request ]
